version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ats_db
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    networks:
      - elk
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=elastic/kibana/kibana-token=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjp1eUJMRVBtQVEtLWpaMVFOeFU2eVpn # Service account token for authentication
      - SERVER_HOST=0.0.0.0 # Ensure Kibana binds to all network interfaces
      - SERVER_NAME=kibana # Provide a name for the Kibana server
      - xpack.encryptedSavedObjects.encryptionKey=664c5acce64232383ca873370e3f64d0
      - xpack.reporting.encryptionKey=5dfdd78c058d23bf970048b6a72456a5
      - xpack.security.encryptionKey=20f573245529c3618782cc9c0bce7971

    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml # Mount the kibana.yml file

volumes:
  mysql_data:
  esdata:

networks:
  elk:
